### ISSUE TITLE
A way of knowing if RTL/LTR was chosen to create a wrapper MUI component (to make RTL work on all MUI components).

### ISSUE THREAD

**Issue by itayperry** [literalpie/storybook-addon-rtl#15]
Hi, 

When using React's MUI, setting direction using `dir` or `document.dir` doesn't work perfectly and an extra library must be installed (`pnpm i stylis-plugin-rtl`).
Is there a way of knowing what the value of the addon is? Some global value or event? 

In the previous package it seems like there was a way to do it:

```tsx
import addons from '@storybook/addons';
import { Direction_MODE_EVENT_NAME } from 'storybook-rtl-addon';

// get channel to listen to event emitter
const channel = addons.getChannel();

// create a component that listens for the event change
function MyComponent({ children }) {
  // this example uses hook but you can also use class component as well
  const [direction, setDirection] = useState();

  useEffect(() => {
    // listen to direction change
    channel.on(Direction_MODE_EVENT_NAME, setDirection);
    return () => channel.off(Direction_MODE_EVENT_NAME, setDirection);
  }, [channel, setDirection]);

  return <div dir={direction}>{children}</div>;
}
```

I'd love some advice please :)
Thank you for your time 🌻

**Comment by literalpie** [comment]
Oh no! I accidentally removed the exports needed to do this. I'll get a fix out today

**Comment by itayperry** [comment]
@literalpie 
Wow thank you so much!!! ✨✨✨✨ That was super fast! :)
