### ISSUE TITLE
How to add toolbar icon to toggle direction

### ISSUE THREAD

**Issue by cbebry** [literalpie/storybook-addon-rtl#25]
Hello, thank you for creating this storybook addon.

I have set up this addon using storybook `^8.2.9` and followed the instructions in the README. I see that I can successfully change the direction using the URL parameter, but the video in the README also shows a toggle icon in the toolbar which is clearly changing to/from RTL<->LTR. I do not notice this toolbar icon after setting up the addon. Is there something I'm doing wrong? Or is the video out of date / is there an instruction that is missing from the README?

Thank you for your time.

**Comment by cbebry** [comment]
I have discovered that I was expecting it to show on the main page, but it actually only shows on the specific component's story page. It will not show on docs or any of the pages that have multiple components on it. So maybe not a bug, maybe user error.

**Comment by literalpie** [comment]
Hi, I think you might be running into https://github.com/literalpie/storybook-addon-rtl/issues/12 . Is the "main page" you mention an MDX file, or the documentation created with [autodocs](https://storybook.js.org/docs/writing-docs/autodocs#set-up-automated-documentation)?

**Comment by cbebry** [comment]
#12 does seem to reflect my issue. I believe the main page includes both the configuration/mdx file and the autodocs if I understand them correctly.

**Comment by literalpie** [comment]
Closing as a duplicate
