### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [literalpie/storybook-addon-rtl#8]
Hey @literalpie! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

Thanks for being a part of our addon community!

Joe

**Comment by literalpie** [comment]
I just released v1.0.0 with a full rewrite, including Storybook 8 support! 🎊
