### ISSUE TITLE
Plugin not working due to `dir="ltr"` inside `.storybook-root`

### ISSUE THREAD

**Issue by tounsoo** [literalpie/storybook-addon-rtl#9]
Looks like Storybook is also assigning `dir` inside the `.storybook-root` which is below the html tag the plugin is assigning `dir` to.

<img width="367" alt="image" src="https://github.com/literalpie/storybook-addon-rtl/assets/8681348/b4e2b486-3d53-4c5e-98b4-977c989da1e9">

**Comment by literalpie** [comment]
Hi, thanks for taking the time to report this! However, I'm not able to see the issue you are describing (I'm testing with storybook 8.0.6). For me, the only thing inside storybook-root is the elements from my story.

Are you seeing that this plugin has no effect at all?

If you give more details about what you are seeing, and ideally a full repo where you are seeing this issue, I can take another look.

**Comment by tounsoo** [comment]
Ah, I found the issue, I have another wrapper component that I'm importing that provides a div with a `dir` in it.

Is there a hook that I can use to pass the values in?

**Comment by literalpie** [comment]
I'm not sure exactly what you mean. 
If you want to pass an initial value for a story, you should be able to use the parameter mentioned in the Readme.
If you are wanting to hook into the add-on (either listening to change events, or emitting your own to cause a change) there's an example [here](https://github.com/literalpie/angular-cdk-sb-addon-rtl-example/blob/master/.storybook/directionality/storybook-directionality.service.ts) on how to do that by listening/emitting in the storybook add-on channel using the event ID `storybook/rtl/rtl-initialize` (the example is pretty Angular-specific, but should give you an idea on where to go)
